import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"

const font = Work_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
    title: "Life Counter",
    description: "Generated by vankhai",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${font.className} antialiased`} suppressHydrationWarning>
                {children}
            </body>
        </html>
    )
}
